config/routes.rb
Rails.application.routes.draw do
  resources :calculations
  get 'welcome/index'
  root 'calculations#new'

  # API routes
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :paye
      get 'calculate_paye', to: 'paye#calculate'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calculation.rb
class Calculation < ApplicationRecord
  has_many :calculation_tax_brackets, dependent: :destroy
  has_many :tax_brackets, through: :calculation_tax_brackets

  validates :basic_pay, presence: true
  validates :allowances, presence: true
  validates :gross_pay, presence: true
  validates :taxable_pay, presence: true
  validates :tax, presence: true
  validates :nhif, presence: true
  validates :nssf, presence: true
  validates :tax_relief, presence: true
  validates :paye, presence: true
  validates :net_pay, presence: true

  validate :validate_basic_pay

  def validate_basic_pay
    if basic_pay && basic_pay < 1
      errors.add(:basic_pay, 'Basic pay must be greater than 1')
    end
  end

  def recalculate
    save!
    calculate_gross_pay
    calculate_nssf
    calculate_taxable_pay
    calculate_tax_relief
    generate_tax_brackets
    self.nhif = calculate_nhif
    self.tax = calculate_tax
    calculate_paye
    calculate_net_pay
    save!
  end

  def calculate_gross_pay
    self.gross_pay = basic_pay + allowances
  end

  def calculate_taxable_pay
    self.taxable_pay = gross_pay - nssf
  end

  def calculate_tax_relief
    self.tax_relief = 2400
  end

  def calculate_paye
    self.paye = tax - tax_relief
    self.paye = 0 if paye.negative?
  end

  def calculate_tax
    calculation_tax_brackets.sum(:total).ceil
  end

  def calculate_nssf
    self.nssf = 200
  end

  def calculate_nhif
    return 0 if gross_pay <= 0
    return 150 if gross_pay < 6000

    return 300 if gross_pay > 5999 && gross_pay < 8000
    return 400 if gross_pay > 7999 && gross_pay < 12_000
    return 500 if gross_pay > 11_999 && gross_pay < 15_000
    return 600 if gross_pay > 14_999 && gross_pay < 20_000
    return 750 if gross_pay > 19_999 && gross_pay < 25_000
    return 850 if gross_pay > 24_999 && gross_pay < 30_000
    return 900 if gross_pay > 29_999 && gross_pay < 35_000
    return 950 if gross_pay > 34_999 && gross_pay < 40_000
    return 1000 if gross_pay > 39_999 && gross_pay < 45_000
    return 1100 if gross_pay > 44_999 && gross_pay < 50_000
    return 1200 if gross_pay > 49_999 && gross_pay < 60_000
    return 1300 if gross_pay > 59_999 && gross_pay < 70_000
    return 1400 if gross_pay > 69_999 && gross_pay < 80_000
    return 1500 if gross_pay > 79_999 && gross_pay < 90_000
    return 1600 if gross_pay > 89_999 && gross_pay < 100_000
    return 1700 if gross_pay > 99_999

    0
  end

  def calculate_net_pay
    self.net_pay = gross_pay - paye - nssf - nhif
  end

  def generate_tax_brackets
    calculation_tax_brackets.destroy_all
    TaxBracket.order(min: :asc).each do |bracket|
      if taxable_pay > bracket.min
        amount_to_use = [taxable_pay - bracket.min, bracket.max - bracket.min].min
        calculation_tax_brackets.create(
          tax_bracket: bracket,
          amount: amount_to_use,
          rate: bracket.rate,
          total: amount_to_use * (bracket.rate / 100)
        )
      end
    end
  end
end

app/models/calculation_tax_bracket.rb
class CalculationTaxBracket < ApplicationRecord
  belongs_to :calculation
  belongs_to :tax_bracket
end

app/models/tax_bracket.rb
class TaxBracket < ApplicationRecord
  has_many :calculation_tax_brackets, dependent: :destroy
  has_many :calculations, through: :calculation_tax_brackets

  def human_max
    if max > 32_333.00
      '∞'
    else
      max
    end
  end

  def annual_min
    min * 12
  end

  def annual_max
    if max > 32_333.00
      '∞'
    else
      max * 12
    end
  end
end

app/controllers/api/base_controller.rb
class Api::BaseController < ApplicationController
end

app/controllers/api/v1/paye_controller.rb
class Api::V1::PayeController < Api::BaseController
  def index
    @calculations = Calculation.all
    render json: @calculations
  end

  def calculate
    basic_pay = params[:basic_pay].to_f
    if Calculation.where(basic_pay: basic_pay).exists?
      calculation = Calculation.where(basic_pay: basic_pay).first
    else
      calculation = Calculation.create(basic_pay: basic_pay)
    end
    calculation.recalculate
    render json: calculation, include: [:calculation_tax_brackets => { :include => :tax_bracket }]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calculations_controller.rb
class CalculationsController < ApplicationController
  before_action :set_calculation, only: %i[ show edit update destroy ]

  # GET /calculations or /calculations.json
  def index
    @calculations = Calculation.all
    redirect_to new_calculation_path
  end

  # GET /calculations/1 or /calculations/1.json
  def show
  end

  # GET /calculations/new
  def new
    @calculation = Calculation.new
  end

  # GET /calculations/1/edit
  def edit
  end

  # POST /calculations or /calculations.json
  def create
    @calculation = Calculation.new(calculation_params)

    respond_to do |format|
      if @calculation.save
        @calculation.recalculate
        format.html { redirect_to calculation_url(@calculation), notice: "Calculation was successfully created." }
        format.json { render :show, status: :created, location: @calculation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @calculation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calculations/1 or /calculations/1.json
  def update
    respond_to do |format|
      if @calculation.update(calculation_params)
        @calculation.recalculate
        format.html { redirect_to calculation_url(@calculation), notice: "Calculation was successfully updated." }
        format.json { render :show, status: :ok, location: @calculation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @calculation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calculations/1 or /calculations/1.json
  def destroy
    @calculation.destroy

    respond_to do |format|
      format.html { redirect_to new_calculation_path, notice: "Calculation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calculation
      @calculation = Calculation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def calculation_params
      params.require(:calculation).permit(:basic_pay, :allowances, :gross_pay, :taxable_pay, :tax, :tax_relief, :paye, :nhif, :nssf, :net_pay)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calculations_helper.rb
module CalculationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/calculations/_body.html.erb
<%= render('notice') %>

<% if @calculation.errors.any? %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert" id="error_explanation">
    <h5><%= pluralize(@calculation.errors.count, "error") %> prohibited this calculation from being saved:</h5>

    <ul>
      <% @calculation.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-3">
      <%= render 'form', calculation: @calculation %>
    </div>
    <div class="col-sm">
      <dl class="row">
        <dt class="col-sm-2">Basic Pay</dt>
        <dd class="col-sm-10"><%= number_with_precision(@calculation.basic_pay, precision: 2, delimiter: ',') %></dd>
      </dl>

      <dl class="row">
        <dt class="col-sm-2">Gross Pay</dt>
        <dd class="col-sm-10"><%= number_with_precision(@calculation.gross_pay, precision: 2, delimiter: ',') %></dd>
      </dl>

      <dl class="row">
        <dt class="col-sm-2">NSSF</dt>
        <dd class="col-sm-10"><%= number_with_precision(@calculation.nssf, precision: 2, delimiter: ',') %></dd>
      </dl>

      <dl class="row">
        <dt class="col-sm-2">Tax</dt>
        <dd class="col-sm-10"><%= number_with_precision(@calculation.tax, precision: 2, delimiter: ',') %></dd>
      </dl>

      <dl class="row">
        <dt class="col-sm-2">Tax Relief</dt>
        <dd class="col-sm-10"><%= number_with_precision(@calculation.basic_pay, precision: 2, delimiter: ',') %></dd>
      </dl>

      <dl class="row">
        <dt class="col-sm-2">PAYE</dt>
        <dd class="col-sm-10"><%= number_with_precision(@calculation.paye, precision: 2, delimiter: ',') %></dd>
      </dl>

      <dl class="row">
        <dt class="col-sm-2">NHIF</dt>
        <dd class="col-sm-10"><%= number_with_precision(@calculation.nhif, precision: 2, delimiter: ',') %></dd>
      </dl>

      <dl class="row">
        <dt class="col-sm-2">Net Pay</dt>
        <dd class="col-sm-10"><%= number_with_precision(@calculation.net_pay, precision: 2, delimiter: ',') %></dd>
      </dl>

      <%= link_to 'New Calculation', new_calculation_path, class: 'btn btn-secondary' %>

      <% if @calculation.tax > 0 %>
        <hr>
        <h5>Tax Calculation Breakdown</h5>
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Tax Bracket</th>
              <th>Rate</th>
              <th>Amount Taxed</th>
              <th>Tax</th>
            </tr>
          </thead>
          <tbody>
            <% @calculation.calculation_tax_brackets.all.each do |calc_tax_bracket| %>
              <tr>
                <td><%= number_with_precision(calc_tax_bracket.tax_bracket.min, precision: 2, delimiter: ',') %> - <%= number_with_precision(calc_tax_bracket.tax_bracket.human_max, precision: 2, delimiter: ',') %></td>
                <td><%= number_with_precision(calc_tax_bracket.rate, precision: 0, delimiter: ',') %>%</td>
                <td><%= number_with_precision(calc_tax_bracket.amount, precision: 2, delimiter: ',') %></td>
                <td><%= number_with_precision(calc_tax_bracket.total, precision: 2, delimiter: ',') %></td>
              </tr>
            <% end %>
            <tr>
              <td></td>
              <td></td>
              <td><b>Total Tax</b></td>
              <td><%= number_with_precision(@calculation.tax, precision: 2, delimiter: ',') %></td>
            </tr>
            <tr>
              <td></td>
              <td></td>
              <td><b>Tax Relief</b></td>
              <td><%= number_with_precision(@calculation.tax_relief, precision: 2, delimiter: ',') %></td>
            </tr>
            <tr>
              <td></td>
              <td></td>
              <td><b>PAYE</b></td>
              <td><%= number_with_precision(@calculation.paye, precision: 2, delimiter: ',') %></td>
            </tr>
          </tbody>
        </table>
      <% end %>
    </div>

    <div class="col-sm">
      <hr>
      <h5>API</h5>
      <p>Access this calculation using REST</p>

      <p class="font-monospace text-muted"><%= "https://thetax.co.ke/api/v1/calculate_paye?basic_pay=#{@calculation.basic_pay}" %></p>
      
      <hr>
      <h5>PAYE Brackets</h5>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Taxable Pay (Monthly)</th>
            <th>Taxable Pay (Annual)</th>
            <th>Tax Rate</th>
          </tr>
        </thead>
        <tbody>
          <% TaxBracket.all.each do |bracket| %>
            <tr>
              <td><%= number_with_precision(bracket.min, precision: 2, delimiter: ',') %> - <%= number_with_precision(bracket.human_max, precision: 2, delimiter: ',') %></td>
              <td><%= number_with_precision(bracket.annual_min, precision: 2, delimiter: ',') %> - <%= number_with_precision(bracket.annual_max, precision: 2, delimiter: ',') %></td>
              <td><%= number_with_precision(bracket.rate, precision: 0, delimiter: ',') %>%</td>
            </tr>
          <% end %>
        </tbody>        
      </table>

      <div>
        <h5>What is PAYE?</h5>
        <p>PAYE is the amount of tax you pay on your income. It is calculated by taking the tax rate and multiplying it by your taxable income.</p>
        <hr>
        <h5>What is taxed?</h5>
        <p>The amount of income you pay into the tax system. This includes your basic pay, benefits, and other income.</p>
      </div>
    </div>
  </div>
</div>

app/views/calculations/_form.html.erb
<%= form_with(model: calculation) do |form| %>
  <div class="form-group">
    <%= form.label :basic_pay %>
    <%= form.text_field :basic_pay, class: "form-control" %>
  </div>

  <br>
  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/calculations/_notice.html.erb
<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert" id="notice">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<% if notice %>
  <div class="alert alert-success alert-dismissible fade show" role="alert" id="notice">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/calculations/edit.html.erb
<h3>Editing Calculation</h3>

<%= render('body') %>

app/views/calculations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Calculations</h1>

<table>
  <thead>
    <tr>
      <th>Basic pay</th>
      <th>Allowances</th>
      <th>Gross pay</th>
      <th>Taxable pay</th>
      <th>Tax</th>
      <th>Tax relief</th>
      <th>Paye</th>
      <th>Nhif</th>
      <th>Nssf</th>
      <th>Net pay</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @calculations.each do |calculation| %>
      <tr>
        <td><%= calculation.basic_pay %></td>
        <td><%= calculation.allowances %></td>
        <td><%= calculation.gross_pay %></td>
        <td><%= calculation.taxable_pay %></td>
        <td><%= calculation.tax %></td>
        <td><%= calculation.tax_relief %></td>
        <td><%= calculation.paye %></td>
        <td><%= calculation.nhif %></td>
        <td><%= calculation.nssf %></td>
        <td><%= calculation.net_pay %></td>
        <td><%= link_to 'Show', calculation %></td>
        <td><%= link_to 'Edit', edit_calculation_path(calculation) %></td>
        <td><%= link_to 'Destroy', calculation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Calculation', new_calculation_path %>

app/views/calculations/new.html.erb
<h4>New Calculation</h4>

<%= render('body') %>

app/views/calculations/show.html.erb
<%= render('body') %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Tax Calculator Ke</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaxCalculatorKe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container mt-2">
      <%= yield %>
    </div>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>